---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Rule to tag EC2 instance images, EBS volume snapshots, and RDS database snapshots for deletion. Copyright 2022, Paul Marcelin. https://github.com/sqlxpert/aws-tag-sched-ops/"


# To check YAML syntax, first complete the setup steps
# in aws-tag-sched-ops/requirements.txt and then:
#   cd aws-tag-sched-ops  # Home of .yamllint
#   yamllint cloudformation/age_backups_rule.yaml


# https://github.com/sqlxpert/aws-tag-sched-ops/
#
# Copyright 2022, Paul Marcelin
#
# This file is part of TagSchedOps.
#
# TagSchedOps is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TagSchedOps is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TagSchedOps. If not, see http://www.gnu.org/licenses/


Parameters:

  # Do not validate at CloudFormation level,
  # in case values accepted by underlying APIs change:

  TagSchedOpsAgeRuleScheduleCron:
    Type: String
    Description: "When/how often to tag images/snapshots for deletion, in cron form, for UTC timezone. The default is once a day, at 08:06 UTC (just after midnight Pacific Standard Time or 01:00 Pacific Daylight Time). See https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions"
    Default: "06 08 * * ? *"

  TagSchedOpsAgeRuleTimezoneLocal:
    Type: String
    Description: "The Olson name of your preferred local timezone (for example, \"America/Los_Angeles\"). The default aligns time intervals with the UTC day, which begins at midnight in London, England."
    Default: "UTC"

  TagSchedOpsAgeRuleRetainIntervals:
    Type: String
    Description: "One or more ISO 8601 intervals, repeating or non-, specified as durations. Enclose each interval in single quotes (') and separate multiple intervals with spaces. The default keeps first daily images/snapshots from the past 31 days and tags any others for deletion. Restrictions: no decimal, hour must be 0-4, 6 or 12, minute must be 0, 10, 20 or 30, and second must be 0. See documentation or run: aws-tag-sched-ops/age_backups.py --help"
    Default: "'R31/P1D'"

  TagSchedOpsAgeRuleArgsMisc:
    Type: String
    Description: "Other command-line options to pass to age_backups.py. Spaces are allowed between arguments, but no argument may contain a space. See documentation or run: aws-tag-sched-ops/age_backups.py --help"
    Default: ""

  TagSchedOpsAgeRuleArgsAsList:
    Type: String
    Description: "All command-line options to pass to age_backups.py, as a JSON list of strings. Example (copy everything between the bars, but do not include the bars): |[\"--user-timezone\", \"UTC\", \"--retain-intervals\", \"R31/P1D\"|. This form is cumbersome, but allows spaces within arguments."
    Default: ""

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Basics"
        Parameters:
          - TagSchedOpsAgeRuleScheduleCron
      - Label:
          default: "Easy options (must leave Advanced options entry blank)"
        Parameters:
          - TagSchedOpsAgeRuleTimezoneLocal
          - TagSchedOpsAgeRuleRetainIntervals
          - TagSchedOpsAgeRuleArgsMisc
      - Label:
          default: "Advanced options (leave all Easy options entries blank)"
        Parameters:
          - TagSchedOpsAgeRuleArgsAsList
    ParameterLabels:
      TagSchedOpsAgeRuleScheduleCron:
        default: "Schedule (cron form)"
      TagSchedOpsAgeRuleTimezoneLocal:
        default: "Local timezone"
      TagSchedOpsAgeRuleRetainIntervals:
        default: "Retention policy"
      TagSchedOpsAgeRuleArgsMisc:
        default: "Other command-line options"
      TagSchedOpsAgeRuleArgsAsList:
        default: "All options, in a JSON list of strings"

Conditions:

  TagSchedOpsAgeRuleArgsAsListEmpty:
    !Equals [ !Ref TagSchedOpsAgeRuleArgsAsList, "" ]

Resources:


  TagSchedOpsAgeRule:
    Type: "AWS::Events::Rule"
    DeletionPolicy: Delete
    Properties:
      Description: !If [ TagSchedOpsAgeRuleArgsAsListEmpty, !Sub "${TagSchedOpsAgeRuleScheduleCron} age_backups.py --user-timezone '${TagSchedOpsAgeRuleTimezoneLocal}' --retain-intervals ${TagSchedOpsAgeRuleRetainIntervals} ${TagSchedOpsAgeRuleArgsMisc}", !Sub "${TagSchedOpsAgeRuleScheduleCron} age_backups.py ${TagSchedOpsAgeRuleArgsAsList}" ]
      ScheduleExpression: !Sub "cron(${TagSchedOpsAgeRuleScheduleCron})"
      State: ENABLED
      Targets:
        - Arn: !ImportValue "LambdaFn-TagSchedOpsAge-Arn"
          # Field 6 (counting from 0) of an AWS Lambda
          # function ARN is the function's name, including
          # the random string appended by CloudFormation:
          Id: !Select [ 6, !Split [ ":", !ImportValue "LambdaFn-TagSchedOpsAge-Arn" ] ]
          Input: !If [ TagSchedOpsAgeRuleArgsAsListEmpty, !Sub "\"--user-timezone '${TagSchedOpsAgeRuleTimezoneLocal}' --retain-intervals ${TagSchedOpsAgeRuleRetainIntervals} ${TagSchedOpsAgeRuleArgsMisc}\"", !Ref TagSchedOpsAgeRuleArgsAsList ]


  TagSchedOpsAgeRuleInvokeLambdaPerm:
    Type: "AWS::Lambda::Permission"
    DeletionPolicy: Delete
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Select [ 6, !Split [ ":", !ImportValue "LambdaFn-TagSchedOpsAge-Arn" ] ]
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt TagSchedOpsAgeRule.Arn


  TagSchedOpsAgeRuleDisableLambdaPerm:
    Type: "AWS::Lambda::Permission"
    DeletionPolicy: Delete
    Properties:
      Action: "lambda:DisableInvokeFunction"
      FunctionName: !Select [ 6, !Split [ ":", !ImportValue "LambdaFn-TagSchedOpsAge-Arn" ] ]
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt TagSchedOpsAgeRule.Arn
